"""First magration

Revision ID: 45aeca1197b2
Revises: 
Create Date: 2024-02-04 12:28:55.781892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45aeca1197b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('winter', sa.String(length=2), nullable=True),
    sa.Column('summer', sa.String(length=2), nullable=True),
    sa.Column('autumn', sa.String(length=2), nullable=True),
    sa.Column('spring', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('fam', sa.String(length=32), nullable=False),
    sa.Column('otc', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('pereval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=32), nullable=False),
    sa.Column('other_title', sa.String(length=32), nullable=True),
    sa.Column('add_time', sa.TIMESTAMP(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['level.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('title', sa.String(length=32), nullable=True),
    sa.Column('pereval_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pereval_id'], ['pereval.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    op.drop_table('pereval')
    op.drop_table('user')
    op.drop_table('level')
    # ### end Alembic commands ###
